### ISSUE TITLE
MCRegion to Anvil Converter.

### ISSUE THREAD

**Issue by jrlambs** [ImagicalCorp/MConverterUltimate#9] opened 2016-08-28 16:56 UTC
No matter what I do it spits out the "Usage" message telling me how to run it.  I put my "world" folder in the same directory and ran the start.sh...  I looked at the usage and typed the command myself.. same thing.  Tried in windows and linux.  I'm trying to convert a world from ClearSky so I can use it in Gennisys.... if I just drop the world and start Genisys it crashes :/

**Comment by inxomnyaa** [comment] 2016-09-03 21:56
Confirmed

**Comment by DeathRaven359** [comment] 2016-12-23 21:54
Anyone have a fix for this?

**Comment by k3ithos** [comment] 2016-12-27 23:04
Trying to find a fix, tell me if you have got it before me. I think it's a problem with the script...

**Comment by k3ithos** [comment] 2016-12-28 01:03
Fixed. See https://github.com/ImagicalCorp/MineConvert/blob/master/MCRegion%20to%20Anvil/README.md
If you have any issues with the converter upload your map, send me the link and I'll do what I can.

**Closed as completed** 2016-12-28 01:03 UTC

**Comment by Infernus102** [comment] 2016-12-28 08:24
@keithkfng still, whatever i do output is Usage:

**Comment by k3ithos** [comment] 2016-12-28 08:29
@Infernus102 screenshot of error + what operating system?

**Comment by Infernus102** [comment] 2016-12-28 08:33
![untitled](https://cloud.githubusercontent.com/assets/22660649/21517601/59a17236-cd06-11e6-89e0-ee3514ef965e.png)

![untitled2](https://cloud.githubusercontent.com/assets/22660649/21517602/59a829c8-cd06-11e6-9539-1cb247f0c9ff.png)

![untitled3](https://cloud.githubusercontent.com/assets/22660649/21517773/e832ce86-cd07-11e6-94f5-bbc288f773ae.png)

OS: Windows 10

**Comment by k3ithos** [comment] 2016-12-28 09:11
PocketMine to Anvil?

**Comment by Infernus102** [comment] 2016-12-28 09:13
ya, mcregion world

**Comment by k3ithos** [comment] 2016-12-28 09:21
Send me the link of the map and I'll see what I can do...

**Comment by remotevase** [comment] 2016-12-28 15:03
This seems to be fine for me...
